"""
Module: ddl_generator.py
Purpose: Generates PostgreSQL DDL from transformed IR nodes
Author: Migration Platform Team
Created: 2026-05-22
Domain: Transpilation
Author: Ravi Sharma
Copyright (c) 2026 Ravi Sharma
SPDX-License-Identifier: MIT
"""


from domains.transpilation.ir_models import (
    ColumnDefNode,
    ConstraintNode,
    DataTypeNode,
    IrNode,
)
from shared.kernel.ddl_identifier import quote_pg_ident


class DdlGenerator:
    """Generates PostgreSQL DDL statements from IR nodes."""

    def generate_table_ddl(self, ir_node: IrNode) -> str:
        """Generate CREATE TABLE DDL from an IR node."""
        table_name = ir_node.properties.get("name", "")
        schema_name = ir_node.properties.get("schema", "public")
        if not table_name:
            return ""
        qualified_name = (
            f"{quote_pg_ident(schema_name)}.{quote_pg_ident(table_name)}"
            if schema_name
            else quote_pg_ident(table_name)
        )

        columns = ir_node.children or []
        constraints = ir_node.properties.get("constraints", [])

        parts: list[str] = []
        for col in columns:
            if isinstance(col, ColumnDefNode):
                parts.append(self._generate_column_def(col))

        for constraint in constraints:
            if isinstance(constraint, ConstraintNode):
                parts.append(self._generate_constraint(constraint))

        columns_sql = ",\n  ".join(parts)
        return f"CREATE TABLE {qualified_name} (\n  {columns_sql}\n);"

    def _generate_column_def(self, col: ColumnDefNode) -> str:
        """Generate a single column definition."""
        parts = [self._quote_ident(col.column_name)]

        if col.data_type:
            parts.append(self._generate_data_type(col.data_type))
        else:
            parts.append("TEXT")

        if col.is_identity:
            parts.append("GENERATED BY DEFAULT AS IDENTITY")
        elif col.default_value:
            parts.append(f"DEFAULT {col.default_value}")

        if not col.is_nullable:
            parts.append("NOT NULL")
        if col.is_primary_key:
            parts.append("PRIMARY KEY")

        if col.collation:
            parts.append(f"COLLATE {col.collation}")

        return " ".join(parts)

    def _generate_data_type(self, dt: DataTypeNode) -> str:
        """Generate PostgreSQL data type string."""
        type_name = dt.type_name

        # Map type name to PostgreSQL equivalent
        pg_type = self._map_type(type_name)

        if pg_type in ("NUMERIC", "DECIMAL") and dt.precision is not None:
            if dt.scale is not None:
                return f"{pg_type}({dt.precision}, {dt.scale})"
            return f"{pg_type}({dt.precision})"
        if pg_type in ("VARCHAR", "CHAR", "NCHAR") and dt.max_length is not None:
            if dt.max_length == -1 or dt.max_length > 10485760:
                return "TEXT"
            return f"{pg_type}({dt.max_length})"

        return pg_type

    def _generate_constraint(self, constraint: ConstraintNode) -> str:
        """Generate constraint DDL."""
        name = constraint.constraint_name
        name_part = f"CONSTRAINT {self._quote_ident(name)} " if name else ""

        if constraint.constraint_type == "PRIMARY KEY":
            cols = ", ".join(self._quote_ident(c) for c in constraint.columns)
            return f"{name_part}PRIMARY KEY ({cols})"

        if constraint.constraint_type == "FOREIGN KEY":
            cols = ", ".join(self._quote_ident(c) for c in constraint.columns)
            ref_cols = ", ".join(self._quote_ident(c) for c in constraint.referenced_columns)
            ref_table = self._quote_ident(constraint.referenced_table or "")
            return f"{name_part}FOREIGN KEY ({cols}) REFERENCES {ref_table} ({ref_cols})"

        if constraint.constraint_type == "UNIQUE":
            cols = ", ".join(self._quote_ident(c) for c in constraint.columns)
            return f"{name_part}UNIQUE ({cols})"

        if constraint.constraint_type == "CHECK" and constraint.check_expression:
            return f"{name_part}CHECK ({constraint.check_expression})"

        return ""

    def generate_view_ddl(self, ir_node: IrNode) -> str:
        """Generate CREATE VIEW DDL."""
        view_name = ir_node.properties.get("name", "")
        schema = ir_node.properties.get("schema", "public")
        if not view_name:
            return ""
        qualified = f"{quote_pg_ident(schema)}.{quote_pg_ident(view_name)}"
        select_sql = ir_node.properties.get("select_sql", "")
        return f"CREATE VIEW {qualified} AS\n{select_sql};"

    def generate_index_ddl(self, ir_node: IrNode) -> str:
        """Generate CREATE INDEX DDL."""
        index_name = ir_node.properties.get("name", "")
        table_name = ir_node.properties.get("table_name", "")
        schema = ir_node.properties.get("schema", "public")
        columns = ir_node.properties.get("columns", [])
        unique = ir_node.properties.get("unique", False)
        where = ir_node.properties.get("filter_definition", "")
        if not table_name:
            return ""

        unique_str = "UNIQUE " if unique else ""
        cols_str = ", ".join(self._quote_ident(c) for c in columns)
        ddl = f"CREATE {unique_str}INDEX {self._quote_ident(index_name)} ON {quote_pg_ident(schema)}.{self._quote_ident(table_name)} ({cols_str})"
        if where:
            ddl += f" WHERE {where}"
        return ddl + ";"

    def generate_index_ddl_from_discovery(
        self,
        schema: str,
        table: str,
        index_name: str,
        key_columns: list[str],
        is_unique: bool = False,
        include_columns: list[str] | None = None,
        filter_definition: str | None = None,
    ) -> str:
        """Fix F.5: generate PostgreSQL CREATE INDEX from DiscoveredIndex metadata.

        Differences from generate_index_ddl (which takes an IrNode):
        - Accepts plain strings instead of an IR node.
        - Supports INCLUDE columns (PostgreSQL covering index).
        - Primary key indexes are handled separately via table DDL; callers should
          filter is_primary_key=True before calling this method.
        """
        if not key_columns:
            return ""
        unique_str = "UNIQUE " if is_unique else ""
        cols_str = ", ".join(quote_pg_ident(c) for c in key_columns)
        qualified_table = f"{quote_pg_ident(schema)}.{quote_pg_ident(table)}"
        ddl = (
            f"CREATE {unique_str}INDEX {quote_pg_ident(index_name)} "
            f"ON {qualified_table} ({cols_str})"
        )
        if include_columns:
            inc_str = ", ".join(quote_pg_ident(c) for c in include_columns)
            ddl += f" INCLUDE ({inc_str})"
        if filter_definition:
            ddl += f" WHERE {filter_definition}"
        return ddl + ";"

    def generate_comment(self, obj_type: str, name: str, comment: str, schema: str = "public") -> str:
        """Generate COMMENT ON DDL."""
        return f"COMMENT ON {obj_type} {quote_pg_ident(schema)}.{quote_pg_ident(name)} IS '{comment}';"

    @staticmethod
    def _quote_ident(name: str) -> str:
        """Quote an identifier for PostgreSQL, escaping embedded double-quotes."""
        if not name:
            return ""
        return quote_pg_ident(name)

    @staticmethod
    def _map_type(tsql_type: str) -> str:
        """Map a T-SQL type name to PostgreSQL type name."""
        mapping = {
            "INT": "INTEGER",
            "INTEGER": "INTEGER",
            "BIGINT": "BIGINT",
            "SMALLINT": "SMALLINT",
            "TINYINT": "SMALLINT",
            "BIT": "BOOLEAN",
            "DECIMAL": "NUMERIC",
            "NUMERIC": "NUMERIC",
            "MONEY": "NUMERIC",
            "SMALLMONEY": "NUMERIC",
            "FLOAT": "DOUBLE PRECISION",
            "REAL": "REAL",
            "DATETIME": "TIMESTAMP",
            "DATETIME2": "TIMESTAMP",
            "SMALLDATETIME": "TIMESTAMP",
            "DATE": "DATE",
            "TIME": "TIME",
            "DATETIMEOFFSET": "TIMESTAMPTZ",
            "CHAR": "CHAR",
            "VARCHAR": "VARCHAR",
            "NVARCHAR": "VARCHAR",
            "NCHAR": "CHAR",
            "TEXT": "TEXT",
            "NTEXT": "TEXT",
            "BINARY": "BYTEA",
            "VARBINARY": "BYTEA",
            "IMAGE": "BYTEA",
            "UNIQUEIDENTIFIER": "UUID",
            "XML": "XML",
            "JSON": "JSONB",
            "SQL_VARIANT": "JSONB",
            "ROWVERSION": "BYTEA",
            "GEOGRAPHY": "GEOGRAPHY",
            "GEOMETRY": "GEOMETRY",
            "HIERARCHYID": "LTREE",
        }
        return mapping.get(tsql_type.upper(), tsql_type.upper())
