# Bootstrap system prerequisites for SQL Optima (Windows).
# Installs Python 3.11+, Node.js LTS, and Go 1.23+ when missing via winget or direct download.

param (
    [switch]$Yes
)

$ErrorActionPreference = "Stop"

$LocalRoot = Join-Path $env:LOCALAPPDATA "sqloptima"
$PathEnvFile = Join-Path $LocalRoot "path.env"
$GoVersion = if ($env:SQLOPTIMA_GO_VERSION) { $env:SQLOPTIMA_GO_VERSION } else { "1.23.6" }

function Write-Info { param($m) Write-Host "  > $m" -ForegroundColor Cyan }
function Write-Ok   { param($m) Write-Host "  v $m" -ForegroundColor Green }
function Write-Warn { param($m) Write-Host "  ! $m" -ForegroundColor Yellow }

New-Item -ItemType Directory -Force -Path $LocalRoot | Out-Null

function Save-PathEnv {
    $lines = @("# Generated by scripts/bootstrap_prereqs.ps1")
    $lines += "PATH=$env:PATH"
    if ($env:GOROOT) { $lines += "GOROOT=$env:GOROOT" }
    $lines | Set-Content -Path $PathEnvFile -Encoding UTF8
}

function Test-Python311 {
    foreach ($cmd in @("python", "python3")) {
        $exe = Get-Command $cmd -ErrorAction SilentlyContinue
        if (-not $exe) { continue }
        try {
            $ver = & $cmd -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>$null
            if ($ver -match '^3\.(1[1-9]|[2-9][0-9])') { return $true }
        } catch {}
    }
    foreach ($minor in @("13", "12", "11")) {
        $py = Get-Command py -ErrorAction SilentlyContinue
        if (-not $py) { break }
        try {
            $ver = & py "-3.$minor" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>$null
            if ($ver -match '^3\.') { return $true }
        } catch {}
    }
    return $false
}

function Install-WithWinget {
    param([string]$Id, [string]$Label)
    $winget = Get-Command winget -ErrorAction SilentlyContinue
    if (-not $winget) { return $false }
    Write-Info "Installing $Label via winget ($Id)..."
    try {
        & winget install --id $Id -e --accept-package-agreements --accept-source-agreements --scope user 2>$null | Out-Null
        return $true
    } catch {
        try {
            & winget install --id $Id -e --accept-package-agreements --accept-source-agreements 2>$null | Out-Null
            return $true
        } catch {
            return $false
        }
    }
}

function Ensure-Python {
    if (Test-Python311) {
        Write-Ok "Python available"
        return
    }
    Write-Warn "Python 3.11+ not found — installing..."
    Install-WithWinget "Python.Python.3.12" "Python 3.12" | Out-Null
    if (-not (Test-Python311)) {
        throw "Python 3.11+ is required. Install from https://www.python.org/downloads/ (check Add to PATH)."
    }
    Write-Ok "Python installed"
}

function Ensure-Node {
    $npm = Get-Command npm -ErrorAction SilentlyContinue
    if ($npm) {
        Write-Ok "npm $(npm --version 2>$null)"
        return
    }
    Write-Warn "Node.js / npm not found — installing..."
    if (Install-WithWinget "OpenJS.NodeJS.LTS" "Node.js LTS") {
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" +
                    [System.Environment]::GetEnvironmentVariable("Path", "User")
    }
    $npm = Get-Command npm -ErrorAction SilentlyContinue
    if ($npm) {
        Write-Ok "npm $(npm --version 2>$null)"
        return
    }
    throw "Node.js install failed. Install from https://nodejs.org/ and re-run."
}

function Test-GoVersion {
    $go = Get-Command go -ErrorAction SilentlyContinue
    if (-not $go) { return $false }
    $out = & go version 2>$null
    if ($out -match 'go(\d+)\.(\d+)') {
        return ([int]$Matches[1] -ge 1 -and [int]$Matches[2] -ge 23)
    }
    return $false
}

function Ensure-Go {
    if (Test-GoVersion) {
        Write-Ok "$(go version 2>$null)"
        return
    }
    Write-Warn "Go 1.23+ not found — installing..."
    if (Install-WithWinget "GoLang.Go" "Go") {
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" +
                    [System.Environment]::GetEnvironmentVariable("Path", "User")
    }
    if (Test-GoVersion) {
        Write-Ok "$(go version 2>$null)"
        return
    }

    Write-Info "Downloading Go $GoVersion..."
    $arch = if ([Environment]::Is64BitOperatingSystem) { "amd64" } else { "386" }
    $zip = "go$GoVersion.windows-$arch.zip"
    $url = "https://go.dev/dl/$zip"
    $zipPath = Join-Path $LocalRoot $zip
    $goRoot = Join-Path $LocalRoot "go"
    Invoke-WebRequest -Uri $url -OutFile $zipPath -UseBasicParsing
    if (Test-Path $goRoot) { Remove-Item -Recurse -Force $goRoot }
    Expand-Archive -Path $zipPath -DestinationPath $LocalRoot -Force
    Remove-Item $zipPath -Force
    $env:GOROOT = $goRoot
    $env:Path = "$goRoot\bin;" + $env:Path
    if (-not (Test-GoVersion)) {
        throw "Go install failed. Install from https://go.dev/dl/"
    }
    Write-Ok "$(go version 2>$null) ($goRoot\bin)"
}

Write-Host ""
Write-Host "  Bootstrapping prerequisites..." -ForegroundColor White
Ensure-Python
Ensure-Node
Ensure-Go
Save-PathEnv
Write-Host ""
match '^[yY](es)?$')
}

Write-Host ""
Write-Host "  Bootstrapping prerequisites..." -ForegroundColor White

$missing = $false
if (-not (Test-Python311)) { $missing = $true }
if (-not (Get-Command npm -ErrorAction SilentlyContinue)) { $missing = $true }
if (-not (Test-GoVersion)) { $missing = $true }

if ($missing) {
    if (-not (Ask-Permission)) {
        Write-Host ""
        Write-Warn "Bootstrap cancelled by user. Please install prerequisites manually:"
        Write-Host "    - Python 3.11+"
        Write-Host "    - Node.js LTS"
        Write-Host "    - Go 1.23+"
        Write-Host ""
        exit 0
    }
}

Ensure-Python
Ensure-Node
Ensure-Go
Save-PathEnv
Write-Host ""
