#!/usr/bin/env bash
# Bootstrap system prerequisites for SQL Optima (Linux / macOS).
# Installs Python venv support, Node.js 20+, and Go 1.23+ when missing.
# Writes PATH hints to ~/.local/sqloptima/path.env for child processes.
set -euo pipefail

LOCAL_ROOT="${HOME}/.local/sqloptima"
PATH_ENV="${LOCAL_ROOT}/path.env"
GO_VERSION="${SQLOPTIMA_GO_VERSION:-1.23.6}"
NODE_VERSION="${SQLOPTIMA_NODE_VERSION:-20.18.1}"

info() { echo "  → $*"; }
ok()   { echo "  ✓ $*"; }
warn() { echo "  ⚠ $*"; }

mkdir -p "$LOCAL_ROOT"

maybe_sudo() {
    if [ "$(id -u)" -eq 0 ]; then
        "$@"
    elif command -v sudo &>/dev/null; then
        sudo "$@"
    else
        return 1
    fi
}

detect_pkg_manager() {
    if command -v apt-get &>/dev/null; then echo apt; return; fi
    if command -v dnf &>/dev/null; then echo dnf; return; fi
    if command -v yum &>/dev/null; then echo yum; return; fi
    if command -v pacman &>/dev/null; then echo pacman; return; fi
    if command -v zypper &>/dev/null; then echo zypper; return; fi
    if command -v brew &>/dev/null; then echo brew; return; fi
    echo none
}

write_path_env() {
    {
        echo "# Generated by scripts/bootstrap_prereqs.sh — do not edit"
        echo "PATH=${PATH}"
        if [ -n "${GOROOT:-}" ]; then
            echo "GOROOT=${GOROOT}"
        fi
    } >"$PATH_ENV"
}

python_minor() {
    local py="$1"
    "$py" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || true
}

find_python() {
    for candidate in python3.13 python3.12 python3.11 python3 python; do
        if command -v "$candidate" &>/dev/null; then
            local minor
            minor=$(python_minor "$candidate")
            local major=${minor%%.*}
            local min=${minor#*.}
            if [ -n "$major" ] && [ "$major" -ge 3 ] && [ "$min" -ge 11 ]; then
                echo "$candidate"
                return 0
            fi
        fi
    done
    return 1
}

ensure_python() {
    local py
    if ! py=$(find_python); then
        warn "Python 3.11+ not found — attempting package-manager install..."
        local pm
        pm=$(detect_pkg_manager)
        case "$pm" in
            apt)
                maybe_sudo apt-get update -qq || true
                maybe_sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
                    python3 python3-venv python3-pip curl ca-certificates tar xz-utils || true
                ;;
            dnf)
                maybe_sudo dnf install -y python3 python3-pip curl tar xz || true
                ;;
            yum)
                maybe_sudo yum install -y python3 python3-pip curl tar xz || true
                ;;
            pacman)
                maybe_sudo pacman -Sy --noconfirm python python-pip curl tar xz || true
                ;;
            brew)
                brew install python@3.12 || true
                ;;
        esac
        py=$(find_python) || {
            echo "  ✗ Python 3.11+ is required. Install from https://www.python.org/downloads/"
            return 1
        }
    fi
    ok "Python available ($("$py" --version 2>&1 | head -1))"

    if ! "$py" -m venv --help &>/dev/null; then
        info "Installing Python venv module..."
        local pm
        pm=$(detect_pkg_manager)
        case "$pm" in
            apt)
                maybe_sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python3-venv python3-pip || true
                ;;
            dnf) maybe_sudo dnf install -y python3-devel || true ;;
            brew) brew install python@3.12 || true ;;
        esac
    fi

    if ! "$py" -m pip --version &>/dev/null; then
        info "Bootstrapping pip via ensurepip..."
        "$py" -m ensurepip --upgrade 2>/dev/null || true
    fi
}

arch_tag() {
    local machine
    machine="$(uname -m)"
    case "$machine" in
        x86_64|amd64) echo amd64 ;;
        aarch64|arm64) echo arm64 ;;
        *) echo "$machine" ;;
    esac
}

os_tag() {
    case "$(uname -s)" in
        Darwin) echo darwin ;;
        Linux) echo linux ;;
        *) echo linux ;;
    esac
}

ensure_node() {
    if command -v npm &>/dev/null; then
        ok "npm $(npm --version)"
        return 0
    fi

    warn "Node.js / npm not found — installing..."
    local pm
    pm=$(detect_pkg_manager)
    case "$pm" in
        apt)
            maybe_sudo apt-get update -qq || true
            maybe_sudo DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs npm curl ca-certificates \
                || maybe_sudo DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs npm
            ;;
        dnf) maybe_sudo dnf install -y nodejs npm || true ;;
        yum) maybe_sudo yum install -y nodejs npm || true ;;
        pacman) maybe_sudo pacman -Sy --noconfirm nodejs npm || true ;;
        brew) brew install node || true ;;
    esac

    if command -v npm &>/dev/null; then
        ok "npm $(npm --version) (package manager)"
        return 0
    fi

    info "Downloading Node.js ${NODE_VERSION} to ${LOCAL_ROOT}..."
    local arch os dir tarball
    arch=$(arch_tag)
    os=$(os_tag)
    dir="${LOCAL_ROOT}/node-v${NODE_VERSION}-${os}-${arch}"
    tarball="node-v${NODE_VERSION}-${os}-${arch}.tar.xz"
    if [ ! -x "${dir}/bin/npm" ]; then
        mkdir -p "$LOCAL_ROOT"
        curl -fsSL "https://nodejs.org/dist/v${NODE_VERSION}/${tarball}" -o "${LOCAL_ROOT}/${tarball}"
        tar -xJf "${LOCAL_ROOT}/${tarball}" -C "$LOCAL_ROOT"
        rm -f "${LOCAL_ROOT}/${tarball}"
    fi
    export PATH="${dir}/bin:${PATH}"
    ok "npm $(npm --version) (${dir}/bin)"
}

go_version_ok() {
    local ver
    ver=$(go env GOVERSION 2>/dev/null | sed 's/^go//')
    if [ -z "$ver" ]; then
        return 1
    fi
    local major minor
    major=$(echo "$ver" | cut -d. -f1)
    minor=$(echo "$ver" | cut -d. -f2)
    [ "$major" -ge 1 ] && [ "$minor" -ge 23 ]
}

ensure_go() {
    if command -v go &>/dev/null && go_version_ok; then
        ok "$(go version)"
        return 0
    fi

    warn "Go 1.23+ not found — installing..."
    local pm
    pm=$(detect_pkg_manager)
    case "$pm" in
        apt)
            maybe_sudo apt-get update -qq || true
            maybe_sudo DEBIAN_FRONTEND=noninteractive apt-get install -y golang-go curl ca-certificates || true
            ;;
        dnf) maybe_sudo dnf install -y golang || true ;;
        yum) maybe_sudo yum install -y golang || true ;;
        pacman) maybe_sudo pacman -Sy --noconfirm go || true ;;
        brew) brew install go || true ;;
    esac

    if command -v go &>/dev/null && go_version_ok; then
        ok "$(go version) (package manager)"
        return 0
    fi

    info "Downloading Go ${GO_VERSION} to ${LOCAL_ROOT}..."
    local arch os tarball
    arch=$(arch_tag)
    os=$(os_tag)
    tarball="go${GO_VERSION}.${os}-${arch}.tar.gz"
    if [ ! -x "${LOCAL_ROOT}/go/bin/go" ]; then
        curl -fsSL "https://go.dev/dl/${tarball}" -o "${LOCAL_ROOT}/${tarball}"
        rm -rf "${LOCAL_ROOT}/go"
        tar -xzf "${LOCAL_ROOT}/${tarball}" -C "$LOCAL_ROOT"
        rm -f "${LOCAL_ROOT}/${tarball}"
    fi
    export GOROOT="${LOCAL_ROOT}/go"
    export PATH="${GOROOT}/bin:${PATH}"
    ok "$(go version) (${GOROOT}/bin)"
}

main() {
    echo ""
    echo "  Bootstrapping prerequisites..."
    ensure_python
    ensure_node
    ensure_go
    write_path_env
    echo ""
}

main "$@"
