"""
Generate postgres_converted_sqlserver_queries.sql by running each T-SQL query
through the converter. This ensures the expected outputs are always in sync
with the actual converter behavior.
Author: Ravi Sharma
Copyright (c) 2026 Ravi Sharma
SPDX-License-Identifier: MIT
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from domains.transpilation.procedural_converter import ProceduralConverter

INPUT_FILE = Path(__file__).parent / "sqlserver_queires_input.sql"
OUTPUT_FILE = Path(__file__).parent / "postgres_converted_sqlserver_queries.sql"

def read_queries(path: Path) -> list[tuple[str, str]]:
    """Read queries from input file. Returns list of (number_label, sql_text) tuples."""
    queries = []
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    # Split on #number patterns at line start
    blocks = re.split(r'^(#\d+)\s+', content, flags=re.MULTILINE)
    # blocks[0] is empty (before first #), blocks[1] is first label, blocks[2] is first query body, etc.
    i = 1
    while i < len(blocks) - 1:
        label = blocks[i].strip()
        sql = blocks[i + 1].strip()
        if sql:
            queries.append((label, sql))
        i += 2
    return queries


def main():
    converter = ProceduralConverter()
    queries = read_queries(INPUT_FILE)
    print(f"Found {len(queries)} queries in {INPUT_FILE.name}")

    outputs = []
    errors = []
    for label, sql in queries:
        result = converter.auto_convert(sql)
        if result.success:
            outputs.append((label, result.converted_sql))
        else:
            errors.append((label, sql, result.errors))
            outputs.append((label, f"-- CONVERSION ERROR: {'; '.join(result.errors)}"))

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("-- PostgreSQL equivalents of T-SQL queries from sqlserver_queires_input.sql\n")
        f.write("-- Auto-generated by generate_converted_queries.py\n")
        f.write("-- Run the converter again to regenerate if needed.\n\n")
        for label, converted in outputs:
            f.write(f"{label} {converted}\n\n")

    print(f"Wrote {len(outputs)} converted queries to {OUTPUT_FILE.name}")
    if errors:
        print(f"\n{len(errors)} conversion errors:")
        for label, sql, errs in errors:
            print(f"  {label}: {'; '.join(errs)}")


if __name__ == "__main__":
    main()
