-- PostgreSQL equivalents of T-SQL queries from sqlserver_queires_input.sql
-- Auto-generated by generate_converted_queries.py
-- Run the converter again to regenerate if needed.

--
-- Author: Ravi Sharma
-- Copyright (c) 2026 Ravi Sharma
-- SPDX-License-Identifier: MIT

#1 SELECT FirstName, LastName FROM Employees ORDER BY LastName NULLS FIRST LIMIT 10

#2 SELECT CURRENT_TIMESTAMP AS CurrentDateTime

#3 SELECT COALESCE(FirstName, '') AS FirstName, COALESCE(LastName, '') AS LastName FROM Users

#4 SELECT LENGTH(CAST(Description AS TEXT)) AS DescLength FROM Products

#5 SELECT POSITION('@' IN Email) AS AtPosition FROM Contacts

#6 SELECT UPPER(FirstName) AS UpperName, LOWER(LastName) AS LowerName FROM People

#7 SELECT RTRIM(LTRIM(Code)) AS CleanCode FROM Items

#8 SELECT ABS(Amount) AS AbsAmount, ROUND(Price, 2) AS RoundedPrice FROM Orders

#9 SELECT CEIL(Tax) AS TaxCeiling, FLOOR(Discount) AS DiscountFloor FROM Invoices

#10 SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS UtcNow

#11 SELECT LASTVAL() AS LastId

#12 SELECT LASTVAL() AS LastIdentity

#13 SELECT 0 AS RowsAffected /* @@ROWCOUNT - manual: use GET DIAGNOSTICS in PL/pgSQL; no equivalent in SELECT */

#14 SELECT CURRENT_DATABASE() AS DatabaseName

#15 SELECT INET_SERVER_ADDR()::TEXT AS HostName

#16 SELECT GEN_RANDOM_UUID() AS NewGuid

#17 SELECT SUBSTRING(Description FROM 1 FOR 50) AS ShortDesc FROM Products

#18 SELECT LEFT(CAST(Code AS TEXT), 3) AS Prefix, RIGHT(CAST(Code AS TEXT), 2) AS Suffix FROM Parts

#19 SELECT REPLACE(Title, 'Old', 'New') AS UpdatedTitle FROM Articles

#20 SELECT REPEAT('*', Rating) AS Stars FROM Reviews

#21 SELECT REVERSE(Name) AS ReversedName FROM Categories

#22 SELECT OVERLAY(Phone PLACING '***' FROM 1 FOR 3) AS MaskedPhone FROM Contacts

#23 SELECT REPEAT(' ', 5) AS FiveSpaces

#24 SELECT CAST(Price AS DECIMAL(10, 2)) AS PriceDec FROM Products

#25 SELECT CAST(TO_CHAR(OrderDate, 'MM/DD/YYYY') AS VARCHAR(10)) AS OrderDateStr FROM Orders

#26 SELECT CAST(Value AS INT) AS SafeInt FROM DataImport

#27 SELECT CAST(Amount AS DECIMAL(10, 2)) AS SafeAmount FROM Transactions

#28 SELECT COALESCE(Phone, Mobile, Email, 'N/A') AS ContactInfo FROM Customers

#29 SELECT NULLIF(Price, 0) AS PriceOrNull FROM Products

#30 SELECT CASE WHEN Status = 1 THEN 'Active' ELSE 'Inactive' END AS StatusText FROM Accounts

#31 SELECT CASE Quarter WHEN 1 THEN 'Q1' WHEN 2 THEN 'Q2' WHEN 3 THEN 'Q3' WHEN 4 THEN 'Q4' END AS QuarterName FROM Sales

#32 SELECT OrderDate + INTERVAL '30 DAY' AS DueDate FROM Orders

#33 SELECT CAST(EXTRACT(epoch FROM CAST(CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS TIMESTAMP) - CAST(CAST(OrderDate AS TIMESTAMP) AS TIMESTAMP)) / 86400 AS BIGINT) AS DaysSince FROM Orders

#34 SELECT EXTRACT(year FROM OrderDate) AS OrderYear, EXTRACT(month FROM OrderDate) AS OrderMonth FROM Orders

#35 SELECT YEAR(OrderDate) AS OrderYear, MONTH(OrderDate) AS OrderMonth, DAY(OrderDate) AS OrderDay FROM Orders

#36 SELECT CAST(DATE_TRUNC('MONTH', CAST(OrderDate AS DATE)) + INTERVAL '1 MONTH' - INTERVAL '1 DAY' AS DATE) AS EndOfMonth FROM Orders

#37 SELECT TO_CHAR(OrderDate, 'YYYY-MM-DD') AS FormattedDate FROM Orders

#38 SELECT STRING_AGG(Name, ', ') AS AllNames FROM Employees

#39 SELECT UNNEST(STRING_TO_ARRAY('a,b,c', ',')) AS Parts

#40 SELECT ROW_NUMBER() OVER (ORDER BY Salary DESC NULLS LAST) AS Rank, Name, Salary FROM Employees

#41 SELECT RANK() OVER (ORDER BY Score DESC NULLS LAST) AS Rank, Name, Score FROM Results

#42 SELECT DENSE_RANK() OVER (ORDER BY Score DESC NULLS LAST) AS Rank, Name, Score FROM Results

#43 SELECT NTILE(4) OVER (ORDER BY Salary DESC NULLS LAST) AS Quartile, Name, Salary FROM Employees

#44 SELECT LEAD(Salary, 1) OVER (ORDER BY EmployeeId NULLS FIRST) AS NextSalary, Salary FROM Employees

#45 SELECT LAG(Salary, 1) OVER (ORDER BY EmployeeId NULLS FIRST) AS PrevSalary, Salary FROM Employees

#46 SELECT FIRST_VALUE(Name) OVER (ORDER BY Salary DESC NULLS LAST) AS TopEarner FROM Employees

#47 SELECT LAST_VALUE(Name) OVER (ORDER BY Salary DESC NULLS LAST RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS BottomEarner FROM Employees

#48 SELECT (CASE WHEN Address ~ '.*[0\-9].*' THEN LENGTH(REGEXP_MATCHES(Address, '.*[0\-9].*')[1]) - 1 ELSE 0 END) /* WARNING: PATINDEX LIKE pattern -> regex */ AS FirstDigitPos FROM Customers

#49 SELECT CAST(Price AS VARCHAR(20)) AS PriceStr FROM Products

#50 SELECT CAST('2024-01-15' AS DATE) /* WARNING: PARSE culture setting not preserved */ AS ParsedDate

#51 SELECT JSON_EXTRACT_PATH_TEXT(JsonData, 'name') AS Name FROM JsonStore

#52 SELECT JSON_EXTRACT_PATH(JsonData, 'address') AS Address FROM JsonStore

#53 SELECT JSONB_ARRAY_ELEMENTS(JsonData) AS JsonRows FROM JsonStore

#54 SELECT Name, Salary FROM Employees ORDER BY Salary DESC NULLS LAST OFFSET 5 FETCH NEXT 10 ROWS ONLY

#55 SELECT Name, Score FROM Results ORDER BY Score DESC NULLS LAST LIMIT 10 WITH TIES

#56 SELECT (SELECT relname FROM pg_class WHERE oid = object_id) /* OBJECT_NAME conversion */ AS ObjectName FROM sys.objects

#57 SELECT (SELECT oid FROM pg_class WHERE relname = 'Employees') /* OBJECT_ID conversion */ AS ObjectId

#58 SELECT (SELECT character_maximum_length FROM information_schema.columns WHERE table_name = 'Employees' AND column_name = 'FirstName') /* COL_LENGTH conversion */ AS ColLen

#59 SELECT (SELECT attname FROM pg_attribute WHERE attrelid = OBJECT_ID('Employees') AND attnum = 1) /* COL_NAME conversion */ AS FirstCol

#60 SELECT src.*, COALESCE(SUM(CASE WHEN src.Year = '2023' THEN src.Amount END), 0) AS "2023", COALESCE(SUM(CASE WHEN src.Year = '2024' THEN src.Amount END), 0) AS "2024" FROM (SELECT Year, Amount FROM Sales) AS src

#61 SELECT * FROM (SELECT *, 'Sales' AS Department, Sales AS Value UNION ALL SELECT *, 'IT' AS Department, IT AS Value UNION ALL SELECT *, 'HR' AS Department, HR AS Value) AS unpvt

#62 SELECT TO_CHAR(CURRENT_TIMESTAMP, 'TMDay,TMMonth,YYYY') AS USDate

#63 SELECT CAST(CURRENT_TIMESTAMP AS DATE) AS TodayDate

#64 SELECT CAST(CURRENT_TIMESTAMP AS TIME) AS TodayTime

#65 SELECT CURRENT_USER AS LoginName

#66 SELECT CURRENT_USER /* WARNING: ORIGINAL_LOGIN impersonation context has no direct PG equivalent */ AS OrigLogin

#67 SELECT CURRENT_SETTING('application_name', true) /* APP_NAME conversion */ AS AppName

#68 SELECT PG_BACKEND_PID()::TEXT /* WARNING: function has no exact PG equivalent */ AS HostId

#69 SELECT TRUE /* GETANSINULL conversion: ANSI NULL behavior */ AS AnsNullSetting

#70 SELECT COALESCE(NULLIF(Tax, 0), 0.08) AS EffectiveTax FROM Orders

#71 SELECT LEFT(CAST(Name AS TEXT), 1) AS Initial, UPPER(LEFT(CAST(Name AS TEXT), 1)) AS UpperInitial FROM People

#72 SELECT HireDate + INTERVAL '3 MONTH' AS ReviewDate FROM Employees

#73 SELECT CAST(EXTRACT(year FROM AGE(CAST(CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS TIMESTAMP), CAST(CAST(HireDate AS TIMESTAMP) AS TIMESTAMP))) AS BIGINT) AS YearsEmployed FROM Employees

#74 SELECT EXTRACT(quarter FROM OrderDate) AS Quarter, COUNT(*) AS OrderCount FROM Orders GROUP BY EXTRACT(quarter FROM OrderDate)

#75 SELECT CAST(DATE_TRUNC('MONTH', CAST(CURRENT_TIMESTAMP AS DATE)) + INTERVAL '1 MONTH' - INTERVAL '1 DAY' AS DATE) AS LastDayOfMonth

#76 SELECT STRING_AGG(DISTINCT City, ', ') AS UniqueCities FROM Customers

#77 SELECT CAST(TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD') AS VARCHAR(10)) AS CompactDate

#78 SELECT CAST(TO_CHAR(CURRENT_TIMESTAMP, 'DD/MM/YYYY') AS VARCHAR(10)) AS BritishDate

#79 SELECT CAST(TO_CHAR(CURRENT_TIMESTAMP, 'DD.MM.YYYY') AS VARCHAR(10)) AS GermanDate

#80 SELECT 0 /* WARNING: CHECKSUM() has no PostgreSQL equivalent */ AS RowChecksum FROM Employees

#81 SELECT 0 /* WARNING: CHECKSUM_AGG has no direct PostgreSQL equivalent */ AS TableChecksum FROM Employees

#82 SELECT CASE WHEN Score >= 90 THEN 'A' WHEN Score >= 80 THEN 'B' ELSE 'C' END AS Grade FROM Results

#83 SELECT NULLIF(TRIM(Code), '') AS CleanCode FROM Products

#84 SELECT CAST(Amount AS DECIMAL(18, 2)) * 1.1 AS AmountWithTax FROM Invoices

#85 SELECT CAST(Price AS VARCHAR(20)) || ' USD' AS PriceDisplay FROM Products

#86 SELECT OVERLAY((SELECT ', ' || Name FROM Cities) PLACING '' FROM 1 FOR 2) AS CityList

#87 SELECT ROW_NUMBER() OVER (PARTITION BY DepartmentId ORDER BY Salary DESC NULLS LAST) AS DeptRank, Name, Salary FROM Employees

#88 SELECT Name, CAST(Salary AS DECIMAL(18, 2)) AS Salary FROM Employees WHERE Salary > 50000

#89 SELECT CASE WHEN EXISTS(SELECT 1 FROM Orders WHERE CustomerId = c.Id) THEN 'HasOrders' ELSE 'NoOrders' END AS OrderStatus FROM Customers AS c

#90 SELECT LENGTH(CAST(COALESCE(TRIM(Description), '') AS TEXT)) AS CleanLen FROM Articles

#91 SELECT StartTime + INTERVAL '2 HOUR' AS EndTime FROM Appointments

#92 SELECT CAST(EXTRACT(epoch FROM CAST(CAST(EndTime AS TIMESTAMP) AS TIMESTAMP) - CAST(CAST(StartTime AS TIMESTAMP) AS TIMESTAMP)) / 60 AS BIGINT) AS DurationMinutes FROM Appointments

#93 SELECT EXTRACT(DAYOFWEEK FROM OrderDate) AS DayOfWeek FROM Orders

#94 SELECT TO_CHAR(Price, 'FM$999,999,990.00' /* CURRENCY */) /* FORMAT conversion */ AS CurrencyPrice FROM Products

#95 SELECT CAST(123.4567 AS DECIMAL(10, 2)) AS RoundedNum

#96 SELECT 0 /* WARNING: BINARY_CHECKSUM has no PostgreSQL equivalent */ AS RowHash FROM Employees

#97 SELECT COALESCE(CAST(NULLIF(Phone, '') AS VARCHAR(20)), 'No Phone') AS PhoneDisplay FROM Contacts

#98 SELECT CURRENT_TIMESTAMP + INTERVAL '-7 DAY' AS LastWeek

#99 SELECT CAST(EXTRACT(days FROM (CAST(CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS TIMESTAMP) - CAST(CAST(HireDate AS TIMESTAMP) AS TIMESTAMP))) / 7 AS BIGINT) AS WeeksEmployed FROM Employees

#100 SELECT CURRENT_TIMESTAMP AS Now, CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS UtcNow, LASTVAL() AS LastId, GEN_RANDOM_UUID() AS Guid

