"""
Module: post_migration_ddl_generator.py
Purpose: Generate PostgreSQL DDL for post-migration finalize steps.
Author: Ravi Sharma
Copyright (c) 2026 Ravi Sharma
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import re

from domains.migration.deferred_schema_catalog import (
    DeferredCheckConstraint,
    DeferredColumnDefault,
    DeferredForeignKey,
    DeferredIdentityColumn,
    DeferredSecondaryIndex,
)
from domains.transpilation.ddl_generator import DdlGenerator
from shared.kernel.ddl_identifier import quote_pg_ident

_FK_ACTION_MAP = {
    "NO_ACTION": "NO ACTION",
    "CASCADE": "CASCADE",
    "SET_NULL": "SET NULL",
    "SET_DEFAULT": "SET DEFAULT",
}


class PostMigrationDdlGenerator:
    """Emit PostgreSQL DDL statements for deferred schema objects."""

    def generate_identity_finalize(
        self,
        target_schema: str,
        table_name: str,
        column: DeferredIdentityColumn,
    ) -> list[str]:
        qualified = f"{quote_pg_ident(target_schema)}.{quote_pg_ident(table_name)}"
        col_ident = quote_pg_ident(column.column_name)
        seed = max(int(column.seed_value), 1)

        alter = (
            f"ALTER TABLE {qualified} "
            f"ALTER COLUMN {col_ident} ADD GENERATED BY DEFAULT AS IDENTITY"
        )
        if column.increment_value and column.increment_value != 1:
            alter += f" (INCREMENT BY {int(column.increment_value)})"

        setval = (
            f"SELECT setval("
            f"pg_get_serial_sequence('{qualified}', '{column.column_name}'), "
            f"GREATEST("
            f"COALESCE((SELECT MAX({col_ident}) FROM {qualified}), 0), "
            f"{seed}"
            f"), "
            f"true"
            f")"
        )
        return [alter + ";", setval + ";"]

    def generate_column_type_cast(
        self,
        target_schema: str,
        table_name: str,
        column_name: str,
        final_pg_type: str,
        using_sql: str,
    ) -> str:
        qualified = f"{quote_pg_ident(target_schema)}.{quote_pg_ident(table_name)}"
        col_ident = quote_pg_ident(column_name)
        return (
            f"ALTER TABLE {qualified} "
            f"ALTER COLUMN {col_ident} TYPE {final_pg_type} "
            f"USING {using_sql};"
        )

    def generate_secondary_index(
        self,
        target_schema: str,
        table_name: str,
        index: DeferredSecondaryIndex,
        *,
        concurrently: bool = False,
    ) -> str | None:
        if index.unsupported_reason:
            return None
        if not index.key_columns:
            return None
        base = DdlGenerator().generate_index_ddl_from_discovery(
            schema=target_schema,
            table=table_name,
            index_name=index.index_name,
            key_columns=index.key_columns,
            is_unique=index.is_unique,
            include_columns=index.include_columns or None,
            filter_definition=index.filter_definition,
        )
        if concurrently and "UNIQUE" not in base.upper():
            return base.replace("CREATE INDEX", "CREATE INDEX CONCURRENTLY", 1)
        return base

    def generate_foreign_key(
        self,
        target_schema: str,
        table_name: str,
        fk: DeferredForeignKey,
        *,
        target_schema_resolver: dict[str, str] | None = None,
    ) -> list[str]:
        if fk.is_disabled or not fk.columns or not fk.referenced_table:
            return []
        qualified = f"{quote_pg_ident(target_schema)}.{quote_pg_ident(table_name)}"
        ref_schema = target_schema
        if target_schema_resolver:
            ref_schema = target_schema_resolver.get(
                fk.referenced_schema.lower(), target_schema
            )
        ref_table = (
            f"{quote_pg_ident(ref_schema)}.{quote_pg_ident(fk.referenced_table)}"
        )
        cols = ", ".join(quote_pg_ident(c) for c in fk.columns)
        ref_cols = ", ".join(quote_pg_ident(c) for c in fk.referenced_columns)
        on_delete = _FK_ACTION_MAP.get(fk.on_delete.upper().replace(" ", "_"), "NO ACTION")
        on_update = _FK_ACTION_MAP.get(fk.on_update.upper().replace(" ", "_"), "NO ACTION")
        add = (
            f"ALTER TABLE {qualified} "
            f"ADD CONSTRAINT {quote_pg_ident(fk.constraint_name)} "
            f"FOREIGN KEY ({cols}) REFERENCES {ref_table} ({ref_cols}) "
            f"ON DELETE {on_delete} ON UPDATE {on_update} NOT VALID"
        )
        validate = (
            f"ALTER TABLE {qualified} "
            f"VALIDATE CONSTRAINT {quote_pg_ident(fk.constraint_name)}"
        )
        return [add + ";", validate + ";"]

    def generate_check_constraint(
        self,
        target_schema: str,
        table_name: str,
        check: DeferredCheckConstraint,
    ) -> list[str]:
        if check.is_disabled:
            return []
        expr = self._transpile_check_expression(check.check_definition)
        if not expr:
            return []
        qualified = f"{quote_pg_ident(target_schema)}.{quote_pg_ident(table_name)}"
        add = (
            f"ALTER TABLE {qualified} "
            f"ADD CONSTRAINT {quote_pg_ident(check.constraint_name)} "
            f"CHECK ({expr}) NOT VALID"
        )
        validate = (
            f"ALTER TABLE {qualified} "
            f"VALIDATE CONSTRAINT {quote_pg_ident(check.constraint_name)}"
        )
        return [add + ";", validate + ";"]

    def generate_column_default(
        self,
        target_schema: str,
        table_name: str,
        default: DeferredColumnDefault,
    ) -> str | None:
        expr = self._transpile_default_expression(default.default_definition)
        if not expr:
            return None
        qualified = f"{quote_pg_ident(target_schema)}.{quote_pg_ident(table_name)}"
        return (
            f"ALTER TABLE {qualified} "
            f"ALTER COLUMN {quote_pg_ident(default.column_name)} "
            f"SET DEFAULT {expr};"
        )

    @staticmethod
    def _transpile_check_expression(definition: str) -> str:
        expr = definition.strip()
        if expr.startswith("(") and expr.endswith(")"):
            expr = expr[1:-1]
        expr = re.sub(r"\[([^\]]+)\]", r'"\1"', expr)
        return (
            expr.replace("getdate()", "CURRENT_TIMESTAMP")
            .replace("GETDATE()", "CURRENT_TIMESTAMP")
        )

    @staticmethod
    def _transpile_default_expression(definition: str) -> str | None:
        expr = definition.strip()
        if expr.startswith("(") and expr.endswith(")"):
            expr = expr[1:-1]
        lowered = expr.lower()
        if lowered in ("getdate()", "sysdatetime()", "sysutcdatetime()"):
            return "CURRENT_TIMESTAMP"
        if lowered in ("newid()", "newsequentialid()"):
            return "gen_random_uuid()"
        if re.match(r"^[\d.]+$", expr):
            return expr
        if expr.startswith("'") and expr.endswith("'"):
            return expr
        return None
