"""
Module: test_post_migration_ddl_generator.py
Purpose: Unit tests for post-migration DDL generation (identity, indexes, constraints).
Author: Ravi Sharma
Copyright (c) 2026 Ravi Sharma
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from domains.migration.deferred_schema_catalog import (
    DeferredCheckConstraint,
    DeferredColumnDefault,
    DeferredForeignKey,
    DeferredIdentityColumn,
    DeferredSecondaryIndex,
)
from domains.migration.post_migration_ddl_generator import PostMigrationDdlGenerator


def test_identity_finalize_ddl_uses_generated_by_default():
    gen = PostMigrationDdlGenerator()
    col = DeferredIdentityColumn(
        column_name="HotelID",
        data_type="int",
        seed_value=1,
        increment_value=1,
    )
    stmts = gen.generate_identity_finalize("public", "Hotels", col)
    joined = "\n".join(stmts)
    assert "GENERATED BY DEFAULT AS IDENTITY" in joined
    assert "setval" in joined
    assert "GREATEST" in joined


def test_secondary_index_ddl_skips_unsupported():
    gen = PostMigrationDdlGenerator()
    idx = DeferredSecondaryIndex(
        index_name="CCI_Hotels",
        is_unique=False,
        is_clustered=True,
        key_columns=["HotelID"],
        unsupported_reason="columnstore",
    )
    assert gen.generate_secondary_index("public", "Hotels", idx) is None


def test_secondary_index_ddl_creates_nonclustered_index():
    gen = PostMigrationDdlGenerator()
    idx = DeferredSecondaryIndex(
        index_name="IX_Hotels_Country",
        is_unique=False,
        is_clustered=False,
        key_columns=["Country"],
    )
    ddl = gen.generate_secondary_index("public", "Hotels", idx)
    assert ddl is not None
    assert "CREATE INDEX" in ddl
    assert "IX_Hotels_Country" in ddl


def test_foreign_key_uses_not_valid_pattern():
    gen = PostMigrationDdlGenerator()
    fk = DeferredForeignKey(
        constraint_name="FK_Orders_Customers",
        columns=["CustomerID"],
        referenced_schema="dbo",
        referenced_table="Customers",
        referenced_columns=["CustomerID"],
        on_delete="NO_ACTION",
        on_update="NO_ACTION",
    )
    stmts = gen.generate_foreign_key("public", "Orders", fk)
    assert len(stmts) == 2
    assert "NOT VALID" in stmts[0]
    assert "VALIDATE CONSTRAINT" in stmts[1]


def test_check_constraint_generates_not_valid_pair():
    gen = PostMigrationDdlGenerator()
    chk = DeferredCheckConstraint(
        constraint_name="CK_Hotels_Rating",
        check_definition="([StarRating]>=(0) AND [StarRating]<=(5))",
    )
    stmts = gen.generate_check_constraint("public", "Hotels", chk)
    assert len(stmts) == 2
    assert "CHECK" in stmts[0]
    assert "NOT VALID" in stmts[0]


def test_column_default_transpiles_getdate():
    gen = PostMigrationDdlGenerator()
    default = DeferredColumnDefault(
        column_name="CreatedDate",
        default_definition="(getdate())",
    )
    ddl = gen.generate_column_default("public", "Hotels", default)
    assert ddl is not None
    assert "SET DEFAULT" in ddl
    assert "CURRENT_TIMESTAMP" in ddl.upper() or "now()" in ddl.lower()
