"""
Module: test_post_migration_finalizer.py
Purpose: Unit tests for post-migration finalize orchestration.
Author: Ravi Sharma
Copyright (c) 2026 Ravi Sharma
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import pytest

from application.go_engine_migration.post_migration_finalizer import PostMigrationFinalizer
from domains.migration.deferred_schema_catalog import (
    DeferredIdentityColumn,
    DeferredSecondaryIndex,
    DeferredTableSchema,
    catalog_to_dict,
)
from domains.migration.post_migration_finalize_models import (
    FinalizeObjectStatus,
    FinalizePhaseStatus,
    PostMigrationFinalizeOptions,
)


class RecordingConnector:
    def __init__(self):
        self.statements: list[str] = []

    async def execute(self, sql: str, *args, **kwargs):
        self.statements.append(sql.strip())
        if sql.strip().upper().startswith("SELECT SETVAL"):
            return [{"setval": 100}]
        return []


@pytest.mark.asyncio
async def test_finalizer_applies_identity_and_index():
    connector = RecordingConnector()
    catalog = DeferredTableSchema(
        source_schema="dbo",
        table_name="Hotels",
        target_schema="public",
        identity_columns=[
            DeferredIdentityColumn(
                column_name="HotelID",
                data_type="int",
                seed_value=1,
                increment_value=1,
            )
        ],
        secondary_indexes=[
            DeferredSecondaryIndex(
                index_name="IX_Hotels_Country",
                key_columns=["Country"],
            )
        ],
    )
    finalizer = PostMigrationFinalizer(connector)
    options = PostMigrationFinalizeOptions(
        finalize_foreign_keys=False,
        finalize_check_constraints=False,
        finalize_defaults=False,
        finalize_triggers=False,
    )
    result = await finalizer.finalize_table(
        catalog,
        options=options,
        schema_map={"dbo": "public"},
    )

    joined = "\n".join(connector.statements)
    assert "GENERATED BY DEFAULT AS IDENTITY" in joined
    assert "CREATE INDEX" in joined
    assert result.status == FinalizePhaseStatus.COMPLETED
    identity_status = next(o for o in result.objects if o.object_type == "identity")
    assert identity_status.status == FinalizeObjectStatus.APPLIED


@pytest.mark.asyncio
async def test_finalizer_skips_unsupported_index():
    connector = RecordingConnector()
    catalog = DeferredTableSchema(
        source_schema="dbo",
        table_name="Hotels",
        target_schema="public",
        secondary_indexes=[
            DeferredSecondaryIndex(
                index_name="CCI_Hotels",
                key_columns=["HotelID"],
                unsupported_reason="columnstore",
            )
        ],
    )
    finalizer = PostMigrationFinalizer(connector)
    options = PostMigrationFinalizeOptions(
        finalize_identities=False,
        finalize_foreign_keys=False,
        finalize_check_constraints=False,
        finalize_defaults=False,
        finalize_triggers=False,
    )
    result = await finalizer.finalize_table(catalog, options=options)

    idx = next(o for o in result.objects if o.object_type == "index")
    assert idx.status == FinalizeObjectStatus.UNSUPPORTED
    assert not any("CREATE INDEX" in s for s in connector.statements)


def test_catalog_dict_embedded_in_plan_config():
    catalog = DeferredTableSchema(
        source_schema="dbo",
        table_name="Hotels",
        target_schema="public",
        identity_columns=[
            DeferredIdentityColumn(column_name="HotelID", data_type="int"),
        ],
    )
    plan_config = {"deferred_schema": catalog_to_dict(catalog)}
    assert plan_config["deferred_schema"]["table_name"] == "Hotels"
    assert plan_config["deferred_schema"]["identity_columns"][0]["column_name"] == "HotelID"
