"""
Module: test_ddl_generator.py
Purpose: Unit tests for PostgreSQL DDL generator
Author: Migration Platform Team
Created: 2026-05-22
Author: Ravi Sharma
Copyright (c) 2026 Ravi Sharma
SPDX-License-Identifier: MIT
"""

import pytest

from domains.transpilation.ddl_generator import DdlGenerator
from domains.transpilation.ir_models import (
    ColumnDefNode,
    DataTypeNode,
    IrNode,
    IrNodeType,
)


@pytest.fixture
def ddl_generator():
    return DdlGenerator()


class TestDdlGenerator:
    def test_generate_table_ddl_basic(self, ddl_generator):
        node = IrNode(node_type=IrNodeType.CREATE_TABLE)
        node.properties["name"] = "users"
        node.properties["schema"] = "public"

        col1 = ColumnDefNode(
            column_name="id",
            data_type=DataTypeNode(type_name="INTEGER", is_nullable=False),
            is_identity=True,
            is_nullable=False,
        )
        col2 = ColumnDefNode(
            column_name="name",
            data_type=DataTypeNode(type_name="VARCHAR", max_length=100),
            is_nullable=True,
        )
        node.children = [col1, col2]

        ddl = ddl_generator.generate_table_ddl(node)
        assert "CREATE TABLE" in ddl
        assert '"public"."users"' in ddl
        assert "id" in ddl
        assert "name" in ddl
        assert "GENERATED BY DEFAULT AS IDENTITY" in ddl

    def test_generate_table_with_not_null(self, ddl_generator):
        node = IrNode(node_type=IrNodeType.CREATE_TABLE)
        node.properties["name"] = "test"

        col = ColumnDefNode(
            column_name="col1",
            data_type=DataTypeNode(type_name="INTEGER"),
            is_nullable=False,
        )
        node.children = [col]

        ddl = ddl_generator.generate_table_ddl(node)
        assert "NOT NULL" in ddl

    def test_generate_table_with_primary_key_constraint(self, ddl_generator):
        node = IrNode(node_type=IrNodeType.CREATE_TABLE)
        node.properties["name"] = "test"

        col = ColumnDefNode(
            column_name="id",
            data_type=DataTypeNode(type_name="INTEGER"),
            is_primary_key=True,
            is_nullable=False,
        )
        node.children = [col]

        ddl = ddl_generator.generate_table_ddl(node)
        assert "PRIMARY KEY" in ddl

    def test_generate_varchar_with_length(self, ddl_generator):
        node = IrNode(node_type=IrNodeType.CREATE_TABLE)
        node.properties["name"] = "test"

        col = ColumnDefNode(
            column_name="name",
            data_type=DataTypeNode(type_name="VARCHAR", max_length=255),
        )
        node.children = [col]

        ddl = ddl_generator.generate_table_ddl(node)
        assert "VARCHAR(255)" in ddl or "varchar(255)" in ddl or "VARCHAR" in ddl

    def test_generate_numeric_with_precision_scale(self, ddl_generator):
        node = IrNode(node_type=IrNodeType.CREATE_TABLE)
        node.properties["name"] = "test"

        col = ColumnDefNode(
            column_name="price",
            data_type=DataTypeNode(type_name="NUMERIC", precision=10, scale=2),
        )
        node.children = [col]

        ddl = ddl_generator.generate_table_ddl(node)
        assert "NUMERIC(10, 2)" in ddl or "numeric(10, 2)" in ddl

    def test_generate_index_ddl(self, ddl_generator):
        node = IrNode(node_type=IrNodeType.CREATE_INDEX)
        node.properties["name"] = "idx_users_name"
        node.properties["table_name"] = "users"
        node.properties["schema"] = "public"
        node.properties["columns"] = ["name"]

        ddl = ddl_generator.generate_index_ddl(node)
        assert "CREATE" in ddl
        assert "idx_users_name" in ddl
        assert "users" in ddl

    def test_generate_unique_index(self, ddl_generator):
        node = IrNode(node_type=IrNodeType.CREATE_INDEX)
        node.properties["name"] = "idx_users_email"
        node.properties["table_name"] = "users"
        node.properties["schema"] = "public"
        node.properties["columns"] = ["email"]
        node.properties["unique"] = True

        ddl = ddl_generator.generate_index_ddl(node)
        assert "UNIQUE" in ddl

    def test_generate_view_ddl(self, ddl_generator):
        node = IrNode(node_type=IrNodeType.CREATE_VIEW)
        node.properties["name"] = "v_users"
        node.properties["schema"] = "public"
        node.properties["select_sql"] = "SELECT id, name FROM users"

        ddl = ddl_generator.generate_view_ddl(node)
        assert "CREATE VIEW" in ddl
        assert "v_users" in ddl

    def test_generate_comment(self, ddl_generator):
        ddl = ddl_generator.generate_comment("TABLE", "users", "User accounts")
        assert "COMMENT ON" in ddl
        assert "users" in ddl

    def test_identifier_quoting(self, ddl_generator):
        quoted = ddl_generator._quote_ident("users")
        assert quoted == '"users"'

    def test_identifier_quoting_empty(self, ddl_generator):
        assert ddl_generator._quote_ident("") == ""
